### ISSUE TITLE
Wrong config output

### ISSUE THREAD

**Issue by Snowb1ind** [naggie/dsnet#65] opened 2022-03-31 13:12 UTC
If you try to use latest master version it creates broken user configs that looks like this :

```
[Interface]
Address=fd00:c6f2:a99b:d600:b3a1:e77f:2380:14a2/22
Address=<nil>/64
PrivateKey=8KkQ3rxeiP4/rZn9SLYtTelCrmM0DAvoN5bvjp0o6Fs=

[Peer]
PublicKey=knQBLoy6mWFDWL+XukG0MPOwHgGTSZwTFFmsM9MFnCI=
PresharedKey=eOUvrmUWVSy5SxtJ70UzxToRwwV5EuFtS/6HKiKvck4=
Endpoint=<Public IP is fine>:51820
PersistentKeepalive=0
AllowedIPs={{10.144.60.0 fffffc00}}
AllowedIPs={{fd00:c6f2:a99b:d600:: ffffffffffffffff0000000000000000}}
```

Cant say when it appeared but [this](https://github.com/naggie/dsnet/commit/8ca08d7ba54a915372ec95dce902b4ad9f481807) commit works.

Checked a few more. [Up to this](https://github.com/naggie/dsnet/commit/e8c0e5ebe862a4f0d6d6be14dd4f59df2fd3a5f7) still works.

**Comment by naggie** [comment] 2022-04-18 20:38
Thanks @Snowb1ind -- now looking into it

**Comment by naggie** [comment] 2022-04-18 20:56
@botto this was caused by https://github.com/naggie/dsnet/pull/59

Here's the output before and after
![image](https://user-images.githubusercontent.com/208440/163876639-a5039a33-343d-48b5-b0d0-7b33e6997dd9.png)

![image](https://user-images.githubusercontent.com/208440/163876543-ddaaa518-5d31-4b99-aa10-cb5aaa4cf310.png)


Note the IPv4 address is `<nil>` too.

**Comment by botto** [comment] 2022-04-25 10:57
Oh, that's not good! I will fix this is asap

**Comment by naggie** [comment] 2022-04-25 12:15
Thanks!

**Comment by botto** [comment] 2022-05-02 22:23
Hi @Snowb1ind That should be fixed now, apologies for the inconvenience

**Comment by botto** [comment] 2022-05-02 22:23
Please close the issue if it works for you too.
I'll do a point release with the fix

**Comment by naggie** [comment] 2022-05-03 08:20
Thanks @botto what branch is the fix on?

**Closed** 2022-05-03 12:29 UTC

**Comment by botto** [comment] 2022-05-03 12:30
Hahaha, I pushed to origin which was my own repo.
Yeah the testing is something I've thought about for a while. I have the test harness I use on dsnet-gui and maybe we could do something around that and send traffic across a small wireguard network

**Comment by naggie** [comment] 2022-05-03 12:37
That's a really good idea. There's no better integration test than actually trying to pass traffic!

**Comment by Snowb1ind** [comment] 2022-05-05 08:17
Forgot to reply. Works perfectly now. Thank you guys 🔥
